### ISSUE TITLE
Default Link Colors

### ISSUE THREAD

**Issue by psullivan6** [registerguard/raptor#15]
Setup the CSS for default link colors and backgrounds. Useful to create default link colors on `:hover`, etc... based on their current color. Ex: white links become black , black links become white, etc...

Example:

``` css
a.white_bg:hover { color: @black; background-color: @grayD;}
a.grayE_bg:hover { color: @black; background-color: @grayC;}
```

**Original idea:**
The background color is `+#222` from its current color, unless it's already too dark in which case it's `-#222`.

**Problem:**
a link that is within another background `div` (or other element) that has a background applied to it. Is it worth creating default `background-color`s?
![hover-issue](https://f.cloud.github.com/assets/2049413/706733/536fe2bc-ddf9-11e2-83b1-dbe4d1cacbfa.png)
