### ISSUE TITLE
Link colors

### ISSUE THREAD

**Issue by mhulse** [registerguard/raptor#34]
Note that if child theme styles come after Raptor theme styles, then there's the possibility of child theme's css trumping Raptor's, like:

``` html
<link rel="stylesheet" href="http://static.registerguard.com/v5/raptor/raptor/css/raptor.min.css">
<link rel="stylesheet" href="{{ WEB }}/assets/styles/adicio.css">
```

``` css
a {
    color: #000;
    text-decoration: none;
}
a:visited { color: #333; }
a:visited:hover,
a:focus,
a:focus:hover,
a:hover,
a:active { color: #ae1a1f; }
```

![link](https://cloud.githubusercontent.com/assets/218624/3281470/0dca0a12-f4af-11e3-81a6-d27eb69fa031.gif)

The Raptor styles should be built so that this does not happen. It's easy enough to do, for example, just account for all types of link states.
